command /gravity:
    trigger:
        if {gravity} is set:
            delete {gravity}
            stop
        set {gravity} to true
        while {gravity} is set:
            loop all blocks in radius 10 of player:
                loop-block is not air
                block at loop-block ~ vector(0, -1, 0) is air
                spawn "falling %loop-block%" parsed as entity type at (location of loop-block ~ vector(0, -0.5, 0)
                set loop-block to air
            wait a tick
