function island(loc: location, r: integer):
  loop all blocks in radius {_r} of {_loc}:
    loop-block is not air
    set {_block} to type of loop-block
    set {_l} to location of loop-block
    set loop-block to air
    summon ("falling %{_block}%" parsed as entitytype) at {_l} with nbt (nbt compound from "{NoGravity:1b}")
    wait 1 tick

command /island <integer>:
  trigger:
    set {_loc} to target block
    island({_loc}, arg-1)
